#!/bin/bash

DIR="`cd "$( dirname "$0" )" && pwd`"

# Split big files
FILES=$DIR/sendbox/files/*
for f in $FILES; do
    if [ -f "$f" ]; then
        if [[ $(stat -c%s $f) -gt 6291456 ]]; then
            echo "Split file $f ($(stat -c%s $f) bytes)"
            pushd "$( dirname "$f" )"
            split -b 6M -d "$(basename "$f")" "$(basename "$f")."
            rm -f "$(basename "$f")"
            popd
        fi
    fi
done


. "$DIR/.funcmail"

# Create emails

FROM="sender@example.com"
SUBJECT="Site backup"
MAILTO="recipient@example.com"
# GPG key to use
KEY="recipient@example.com"

. "$DIR/.config"

# we need two different boundaries: one for an encrypted mail, one for the original
RndStr BOUNDARY 32
RndStr ENCBOUNDARY 32
BODY="This is autogenerated message."


RNDNAME="random";
DIR_EMLS=$DIR/sendbox

FILES=$DIR/sendbox/files/*
for f in $FILES; do
    if [ -f $f ]; then
        echo "Processing $f file ($(stat -c%s $f)).."
        SUBJECT="Site backup. File '$(stat -c%n $f)'"
        RndStr RNDNAME 16
        {
            generate_plain_headers
            printf '%s\n' "--${ENCBOUNDARY}"
            generate_encrypted_section
            {
                generate_multipart_section
                generate_attachment "$f"
                close_multipart_section
            } | gpg -e -a -r $KEY
            printf '%s\n' "--${ENCBOUNDARY}--"
        } > $DIR_EMLS/$RNDNAME.eml
        rm -f "$f"
    fi
done


FILES=$DIR/sendbox/*.eml
for f in $FILES; do
    if [ -f $f ]; then
        echo "Send mail $f file"
        cat "$f" | /usr/sbin/sendmail -f noreply -t -oi
        rm -f "$f"
    fi
done